INSERT INTO Pays(Pays) VALUES("Afghanistan");
INSERT INTO Pays(Pays) VALUES("Albanie");
INSERT INTO Pays(Pays) VALUES("Antarctique");
INSERT INTO Pays(Pays) VALUES("Algérie");
INSERT INTO Pays(Pays) VALUES("Samoa Américaines");
INSERT INTO Pays(Pays) VALUES("Andorre");
INSERT INTO Pays(Pays) VALUES("Angola");
INSERT INTO Pays(Pays) VALUES("Antigua-et-Barbuda");
INSERT INTO Pays(Pays) VALUES("Azerbaïdjan");
INSERT INTO Pays(Pays) VALUES("Argentine");
INSERT INTO Pays(Pays) VALUES("Australie");
INSERT INTO Pays(Pays) VALUES("Autriche");
INSERT INTO Pays(Pays) VALUES("Bahamas");
INSERT INTO Pays(Pays) VALUES("Bahreïn");
INSERT INTO Pays(Pays) VALUES("Bangladesh");
INSERT INTO Pays(Pays) VALUES("Arménie");
INSERT INTO Pays(Pays) VALUES("Barbade");
INSERT INTO Pays(Pays) VALUES("Belgique");
INSERT INTO Pays(Pays) VALUES("Bermudes");
INSERT INTO Pays(Pays) VALUES("Bhoutan");
INSERT INTO Pays(Pays) VALUES("Bolivie");
INSERT INTO Pays(Pays) VALUES("Bosnie-Herzégovine");
INSERT INTO Pays(Pays) VALUES("Botswana");
INSERT INTO Pays(Pays) VALUES("Île Bouvet");
INSERT INTO Pays(Pays) VALUES("Brésil");
INSERT INTO Pays(Pays) VALUES("Belize");
INSERT INTO Pays(Pays) VALUES("Territoire Britannique de l'Océan Indien");
INSERT INTO Pays(Pays) VALUES("Îles Salomon");
INSERT INTO Pays(Pays) VALUES("Îles Vierges Britanniques");
INSERT INTO Pays(Pays) VALUES("Brunéi Darussalam");
INSERT INTO Pays(Pays) VALUES("Bulgarie");
INSERT INTO Pays(Pays) VALUES("Myanmar");
INSERT INTO Pays(Pays) VALUES("Burundi");
INSERT INTO Pays(Pays) VALUES("Bélarus");
INSERT INTO Pays(Pays) VALUES("Cambodge");
INSERT INTO Pays(Pays) VALUES("Cameroun");
INSERT INTO Pays(Pays) VALUES("Canada");
INSERT INTO Pays(Pays) VALUES("Cap-vert");
INSERT INTO Pays(Pays) VALUES("Îles Caïmanes");
INSERT INTO Pays(Pays) VALUES("République Centrafricaine");
INSERT INTO Pays(Pays) VALUES("Sri Lanka");
INSERT INTO Pays(Pays) VALUES("Tchad");
INSERT INTO Pays(Pays) VALUES("Chili");
INSERT INTO Pays(Pays) VALUES("Chine");
INSERT INTO Pays(Pays) VALUES("Taïwan");
INSERT INTO Pays(Pays) VALUES("Île Christmas");
INSERT INTO Pays(Pays) VALUES("Îles Cocos (Keeling)");
INSERT INTO Pays(Pays) VALUES("Colombie");
INSERT INTO Pays(Pays) VALUES("Comores");
INSERT INTO Pays(Pays) VALUES("Mayotte");
INSERT INTO Pays(Pays) VALUES("République du Congo");
INSERT INTO Pays(Pays) VALUES("République Démocratique du Congo");
INSERT INTO Pays(Pays) VALUES("Îles Cook");
INSERT INTO Pays(Pays) VALUES("Costa Rica");
INSERT INTO Pays(Pays) VALUES("Croatie");
INSERT INTO Pays(Pays) VALUES("Cuba");
INSERT INTO Pays(Pays) VALUES("Chypre");
INSERT INTO Pays(Pays) VALUES("République Tchèque");
INSERT INTO Pays(Pays) VALUES("Bénin");
INSERT INTO Pays(Pays) VALUES("Danemark");
INSERT INTO Pays(Pays) VALUES("Dominique");
INSERT INTO Pays(Pays) VALUES("République Dominicaine");
INSERT INTO Pays(Pays) VALUES("Équateur");
INSERT INTO Pays(Pays) VALUES("El Salvador");
INSERT INTO Pays(Pays) VALUES("Guinée Équatoriale");
INSERT INTO Pays(Pays) VALUES("Éthiopie");
INSERT INTO Pays(Pays) VALUES("Érythrée");
INSERT INTO Pays(Pays) VALUES("Estonie");
INSERT INTO Pays(Pays) VALUES("Îles Féroé");
INSERT INTO Pays(Pays) VALUES("Îles (malvinas) Falkland");
INSERT INTO Pays(Pays) VALUES("Géorgie du Sud et les Îles Sandwich du Sud");
INSERT INTO Pays(Pays) VALUES("Fidji");
INSERT INTO Pays(Pays) VALUES("Finlande");
INSERT INTO Pays(Pays) VALUES("Îles Åland");
INSERT INTO Pays(Pays) VALUES("France");
INSERT INTO Pays(Pays) VALUES("Guyane Française");
INSERT INTO Pays(Pays) VALUES("Polynésie Française");
INSERT INTO Pays(Pays) VALUES("Terres Australes Françaises");
INSERT INTO Pays(Pays) VALUES("Djibouti");
INSERT INTO Pays(Pays) VALUES("Gabon");
INSERT INTO Pays(Pays) VALUES("Géorgie");
INSERT INTO Pays(Pays) VALUES("Gambie");
INSERT INTO Pays(Pays) VALUES("Territoire Palestinien Occupé");
INSERT INTO Pays(Pays) VALUES("Allemagne");
INSERT INTO Pays(Pays) VALUES("Ghana");
INSERT INTO Pays(Pays) VALUES("Gibraltar");
INSERT INTO Pays(Pays) VALUES("Kiribati");
INSERT INTO Pays(Pays) VALUES("Grèce");
INSERT INTO Pays(Pays) VALUES("Groenland");
INSERT INTO Pays(Pays) VALUES("Grenade");
INSERT INTO Pays(Pays) VALUES("Guadeloupe");
INSERT INTO Pays(Pays) VALUES("Guam");
INSERT INTO Pays(Pays) VALUES("Guatemala");
INSERT INTO Pays(Pays) VALUES("Guinée");
INSERT INTO Pays(Pays) VALUES("Guyana");
INSERT INTO Pays(Pays) VALUES("Haïti");
INSERT INTO Pays(Pays) VALUES("Îles Heard et Mcdonald");
INSERT INTO Pays(Pays) VALUES("Saint-Siège (état de la Cité du Vatican)");
INSERT INTO Pays(Pays) VALUES("Honduras");
INSERT INTO Pays(Pays) VALUES("Hong-Kong");
INSERT INTO Pays(Pays) VALUES("Hongrie");
INSERT INTO Pays(Pays) VALUES("Islande");
INSERT INTO Pays(Pays) VALUES("Inde");
INSERT INTO Pays(Pays) VALUES("Indonésie");
INSERT INTO Pays(Pays) VALUES("République Islamique d'Iran");
INSERT INTO Pays(Pays) VALUES("Iraq");
INSERT INTO Pays(Pays) VALUES("Irlande");
INSERT INTO Pays(Pays) VALUES("Israël");
INSERT INTO Pays(Pays) VALUES("Italie");
INSERT INTO Pays(Pays) VALUES("Côte d'Ivoire");
INSERT INTO Pays(Pays) VALUES("Jamaïque");
INSERT INTO Pays(Pays) VALUES("Japon");
INSERT INTO Pays(Pays) VALUES("Kazakhstan");
INSERT INTO Pays(Pays) VALUES("Jordanie");
INSERT INTO Pays(Pays) VALUES("Kenya");
INSERT INTO Pays(Pays) VALUES("République Populaire Démocratique de Corée");
INSERT INTO Pays(Pays) VALUES("République de Corée");
INSERT INTO Pays(Pays) VALUES("Koweït");
INSERT INTO Pays(Pays) VALUES("Kirghizistan");
INSERT INTO Pays(Pays) VALUES("République Démocratique Populaire Lao");
INSERT INTO Pays(Pays) VALUES("Liban");
INSERT INTO Pays(Pays) VALUES("Lesotho");
INSERT INTO Pays(Pays) VALUES("Lettonie");
INSERT INTO Pays(Pays) VALUES("Libéria");
INSERT INTO Pays(Pays) VALUES("Jamahiriya Arabe Libyenne");
INSERT INTO Pays(Pays) VALUES("Liechtenstein");
INSERT INTO Pays(Pays) VALUES("Lituanie");
INSERT INTO Pays(Pays) VALUES("Luxembourg");
INSERT INTO Pays(Pays) VALUES("Macao");
INSERT INTO Pays(Pays) VALUES("Madagascar");
INSERT INTO Pays(Pays) VALUES("Malawi");
INSERT INTO Pays(Pays) VALUES("Malaisie");
INSERT INTO Pays(Pays) VALUES("Maldives");
INSERT INTO Pays(Pays) VALUES("Mali");
INSERT INTO Pays(Pays) VALUES("Malte");
INSERT INTO Pays(Pays) VALUES("Martinique");
INSERT INTO Pays(Pays) VALUES("Mauritanie");
INSERT INTO Pays(Pays) VALUES("Maurice");
INSERT INTO Pays(Pays) VALUES("Mexique");
INSERT INTO Pays(Pays) VALUES("Monaco");
INSERT INTO Pays(Pays) VALUES("Mongolie");
INSERT INTO Pays(Pays) VALUES("République de Moldova");
INSERT INTO Pays(Pays) VALUES("Montserrat");
INSERT INTO Pays(Pays) VALUES("Maroc");
INSERT INTO Pays(Pays) VALUES("Mozambique");
INSERT INTO Pays(Pays) VALUES("Oman");
INSERT INTO Pays(Pays) VALUES("Namibie");
INSERT INTO Pays(Pays) VALUES("Nauru");
INSERT INTO Pays(Pays) VALUES("Népal");
INSERT INTO Pays(Pays) VALUES("Pays-Bas");
INSERT INTO Pays(Pays) VALUES("Antilles Néerlandaises");
INSERT INTO Pays(Pays) VALUES("Aruba");
INSERT INTO Pays(Pays) VALUES("Nouvelle-Calédonie");
INSERT INTO Pays(Pays) VALUES("Vanuatu");
INSERT INTO Pays(Pays) VALUES("Nouvelle-Zélande");
INSERT INTO Pays(Pays) VALUES("Nicaragua");
INSERT INTO Pays(Pays) VALUES("Niger");
INSERT INTO Pays(Pays) VALUES("Nigéria");
INSERT INTO Pays(Pays) VALUES("Niué");
INSERT INTO Pays(Pays) VALUES("Île Norfolk");
INSERT INTO Pays(Pays) VALUES("Norvège");
INSERT INTO Pays(Pays) VALUES("Îles Mariannes du Nord");
INSERT INTO Pays(Pays) VALUES("Îles Mineures Éloignées des États-Unis");
INSERT INTO Pays(Pays) VALUES("États Fédérés de Micronésie");
INSERT INTO Pays(Pays) VALUES("Îles Marshall");
INSERT INTO Pays(Pays) VALUES("Palaos");
INSERT INTO Pays(Pays) VALUES("Pakistan");
INSERT INTO Pays(Pays) VALUES("Panama");
INSERT INTO Pays(Pays) VALUES("Papouasie-Nouvelle-Guinée");
INSERT INTO Pays(Pays) VALUES("Paraguay");
INSERT INTO Pays(Pays) VALUES("Pérou");
INSERT INTO Pays(Pays) VALUES("Philippines");
INSERT INTO Pays(Pays) VALUES("Pitcairn");
INSERT INTO Pays(Pays) VALUES("Pologne");
INSERT INTO Pays(Pays) VALUES("Portugal");
INSERT INTO Pays(Pays) VALUES("Guinée-Bissau");
INSERT INTO Pays(Pays) VALUES("Timor-Leste");
INSERT INTO Pays(Pays) VALUES("Porto Rico");
INSERT INTO Pays(Pays) VALUES("Qatar");
INSERT INTO Pays(Pays) VALUES("Réunion");
INSERT INTO Pays(Pays) VALUES("Roumanie");
INSERT INTO Pays(Pays) VALUES("Fédération de Russie");
INSERT INTO Pays(Pays) VALUES("Rwanda");
INSERT INTO Pays(Pays) VALUES("Sainte-Hélène");
INSERT INTO Pays(Pays) VALUES("Saint-Kitts-et-Nevis");
INSERT INTO Pays(Pays) VALUES("Anguilla");
INSERT INTO Pays(Pays) VALUES("Sainte-Lucie");
INSERT INTO Pays(Pays) VALUES("Saint-Pierre-et-Miquelon");
INSERT INTO Pays(Pays) VALUES("Saint-Vincent-et-les Grenadines");
INSERT INTO Pays(Pays) VALUES("Saint-Marin");
INSERT INTO Pays(Pays) VALUES("Sao Tomé-et-Principe");
INSERT INTO Pays(Pays) VALUES("Arabie Saoudite");
INSERT INTO Pays(Pays) VALUES("Sénégal");
INSERT INTO Pays(Pays) VALUES("Seychelles");
INSERT INTO Pays(Pays) VALUES("Sierra Leone");
INSERT INTO Pays(Pays) VALUES("Singapour");
INSERT INTO Pays(Pays) VALUES("Slovaquie");
INSERT INTO Pays(Pays) VALUES("Viet Nam");
INSERT INTO Pays(Pays) VALUES("Slovénie");
INSERT INTO Pays(Pays) VALUES("Somalie");
INSERT INTO Pays(Pays) VALUES("Afrique du Sud");
INSERT INTO Pays(Pays) VALUES("Zimbabwe");
INSERT INTO Pays(Pays) VALUES("Espagne");
INSERT INTO Pays(Pays) VALUES("Sahara Occidental");
INSERT INTO Pays(Pays) VALUES("Soudan");
INSERT INTO Pays(Pays) VALUES("Suriname");
INSERT INTO Pays(Pays) VALUES("Svalbard etÎle Jan Mayen");
INSERT INTO Pays(Pays) VALUES("Swaziland");
INSERT INTO Pays(Pays) VALUES("Suède");
INSERT INTO Pays(Pays) VALUES("Suisse");
INSERT INTO Pays(Pays) VALUES("République Arabe Syrienne");
INSERT INTO Pays(Pays) VALUES("Tadjikistan");
INSERT INTO Pays(Pays) VALUES("Thaïlande");
INSERT INTO Pays(Pays) VALUES("Togo");
INSERT INTO Pays(Pays) VALUES("Tokelau");
INSERT INTO Pays(Pays) VALUES("Tonga");
INSERT INTO Pays(Pays) VALUES("Trinité-et-Tobago");
INSERT INTO Pays(Pays) VALUES("Émirats Arabes Unis");
INSERT INTO Pays(Pays) VALUES("Tunisie");
INSERT INTO Pays(Pays) VALUES("Turquie");
INSERT INTO Pays(Pays) VALUES("Turkménistan");
INSERT INTO Pays(Pays) VALUES("Îles Turks et Caïques");
INSERT INTO Pays(Pays) VALUES("Tuvalu");
INSERT INTO Pays(Pays) VALUES("Ouganda");
INSERT INTO Pays(Pays) VALUES("Ukraine");
INSERT INTO Pays(Pays) VALUES("L'ex-République Yougoslave de Macédoine");
INSERT INTO Pays(Pays) VALUES("Égypte");
INSERT INTO Pays(Pays) VALUES("Royaume-Uni");
INSERT INTO Pays(Pays) VALUES("Île de Man");
INSERT INTO Pays(Pays) VALUES("République-Unie de Tanzanie");
INSERT INTO Pays(Pays) VALUES("États-Unis");
INSERT INTO Pays(Pays) VALUES("Îles Vierges des États-Unis");
INSERT INTO Pays(Pays) VALUES("Burkina Faso");
INSERT INTO Pays(Pays) VALUES("Uruguay");
INSERT INTO Pays(Pays) VALUES("Ouzbékistan");
INSERT INTO Pays(Pays) VALUES("Venezuela");
INSERT INTO Pays(Pays) VALUES("Wallis et Futuna");
INSERT INTO Pays(Pays) VALUES("Samoa");
INSERT INTO Pays(Pays) VALUES("Yémen");
INSERT INTO Pays(Pays) VALUES("Serbie-et-Monténégro");
INSERT INTO Pays(Pays) VALUES("Zambie");
